CREATE TABLE [dbo].[Employee_Master] (
    [EmployeeICode]                    INT            IDENTITY (1, 1) NOT NULL,
    [CompanyICode]                     INT            NOT NULL,
    [DepartmentICode]                  INT            NOT NULL,
    [DesignationICode]                 INT            NOT NULL,
    [EmployeeNumber]                   CHAR (10)      NULL,
    [EmployeeFirstName]                VARCHAR (50)   NOT NULL,
    [EmployeeLastName]                 VARCHAR (50)   NOT NULL,
    [EmployeeDisplayName]              VARCHAR (20)   NULL,
    [EmployeeCurrentAddress1]          VARCHAR (100)  NULL,
    [EmployeeCurrentAddress2]          VARCHAR (100)  NULL,
    [EmployeeCurrentAddress3]          VARCHAR (100)  NULL,
    [EmployeeCurrentCity]              VARCHAR (50)   NULL,
    [EmployeeCurrentState]             VARCHAR (25)   NULL,
    [EmployeeCurrentCountry]           VARCHAR (25)   NULL,
    [EmployeeCurrentPinCode]           VARCHAR (20)   NULL,
    [EmployeeCurrentPhoneNo]           VARCHAR (20)   NULL,
    [IsSameAsCurrentAddress]           BIT            NULL,
    [EmployeePermanentAddress1]        VARCHAR (100)  NULL,
    [EmployeePermanentAddress2]        VARCHAR (100)  NULL,
    [EmployeePermanentAddress3]        VARCHAR (100)  NULL,
    [EmployeePermanentCity]            VARCHAR (50)   NULL,
    [EmployeePermanentState]           VARCHAR (25)   NULL,
    [EmployeePermanentCountry]         VARCHAR (25)   NULL,
    [EmployeePermanentPinCode]         VARCHAR (20)   NULL,
    [EmployeePermanentPhoneNo]         VARCHAR (20)   NULL,
    [EmployeeMobileNo]                 VARCHAR (20)   NULL,
    [EmployeeFatherName]               VARCHAR (50)   NULL,
    [EmployeeDateofBirth]              DATETIME       NULL,
    [EmployeePersonalEmailId]          VARCHAR (100)  NULL,
    [EmployeeDateOfJoining]            DATETIME       NOT NULL,
    [EmployeeCorporateEmailId]         VARCHAR (100)  NULL,
    [EmployeeIM]                       VARCHAR (50)   NULL,
    [LoginUserName]                    VARCHAR (25)   NULL,
    [LoginPassword]                    VARCHAR (25)   NULL,
    [EmployeeBloodGroupId]             INT            NULL,
    [EmployeePANNo]                    VARCHAR (25)   NULL,
    [EmployeePFNo]                     VARCHAR (25)   NULL,
    [EmployeeESINo]                    VARCHAR (25)   NULL,
    [EmployeeBankName]                 VARCHAR (50)   NULL,
    [EmployeeBankAccountNo]            VARCHAR (25)   NULL,
    [EmployeeMaritalStatus]            CHAR (1)       NULL,
    [EmployeePrimarySkill]             VARCHAR (50)   NULL,
    [EmployeePreviousEmployer]         VARCHAR (100)  NULL,
    [EmployeePreviousExperienceYears]  INT            NULL,
    [EmployeePreviousExperienceMonths] INT            NULL,
    [EmployeeReference1Remarks]        VARCHAR (200)  NULL,
    [EmployeeReference2Remarks]        VARCHAR (200)  NULL,
    [EmployeeBioData]                  IMAGE          NULL,
    [DocumentExtension]                CHAR (10)      NULL,
    [EmployeePhoto]                    IMAGE          NULL,
    [PhotoExtension]                   CHAR (10)      NULL,
    [EmployeeDateofLeaving]            DATETIME       NULL,
    [EmployeeReasonforLeaving]         VARCHAR (200)  NULL,
    [IsActive]                         BIT            NOT NULL,
    [CreatedBy]                        INT            NOT NULL,
    [CreatedDate]                      DATETIME       NOT NULL,
    [ModifiedBy]                       INT            NULL,
    [ModifiedDate]                     DATETIME       NULL,
    [SwipeICode]                       INT            NULL,
    [Location]                         CHAR (2)       NULL,
    [Group_id]                         TINYINT        NULL,
    [shift_id]                         INT            NULL,
    [original_name]                    VARCHAR (100)  NULL,
    [pseudo]                           BIT            NULL,
    [current_technology]               INT            NULL,
    [picture]                          IMAGE          NULL,
    [primary_skill_stream_id]          INT            NULL,
    [emp_photo]                        VARCHAR (2000) NULL,
    [night_shift]                      BIT            NULL,
    CONSTRAINT [PK_Employee_Master] PRIMARY KEY CLUSTERED ([EmployeeICode] ASC),
    CONSTRAINT [uk_emp_username] UNIQUE NONCLUSTERED ([LoginUserName] ASC)
);

