//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailDetail_TaskNotCompleted
    {
        public string Task { get; set; }
        public Nullable<int> Assigned_By { get; set; }
        public string Priority { get; set; }
        public string Comments { get; set; }
        public System.DateTime Allocated_Date { get; set; }
        public Nullable<System.DateTime> Completed_date { get; set; }
        public Nullable<int> Overdue_Days { get; set; }
        public Nullable<int> Meeting_Id { get; set; }
        public string Employee_EmailAddress { get; set; }
        public string Employee_FirstName { get; set; }
    }
}
