//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Meeting_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MMS_Meeting_Master()
        {
            this.MMS_Attachment = new HashSet<MMS_Attachment>();
            this.MMS_Meeting_Details = new HashSet<MMS_Meeting_Details>();
            this.MMS_Meeting_Participant = new HashSet<MMS_Meeting_Participant>();
            this.MMS_Notifications = new HashSet<MMS_Notifications>();
        }
    
        public int Meeting_Id { get; set; }
        public string Meeting_Objective { get; set; }
        public System.DateTime Meeting_Date { get; set; }
        public string Meeting_Time { get; set; }
        public string Meeting_Venue { get; set; }
        public string Meeting_Type { get; set; }
        public string Meeting_Duration { get; set; }
        public string Meeting_Department { get; set; }
        public Nullable<int> Meeting_Chairperson { get; set; }
        public string Minutes_Of_Meeting { get; set; }
        public int Meeting_No_Of_Participants { get; set; }
        public Nullable<bool> istemplate { get; set; }
        public Nullable<int> TemplateID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MMS_Attachment> MMS_Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MMS_Meeting_Details> MMS_Meeting_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MMS_Meeting_Participant> MMS_Meeting_Participant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MMS_Notifications> MMS_Notifications { get; set; }
    }
}
