//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Meeting_Template_Users
    {
        public int uid { get; set; }
        public Nullable<int> tid { get; set; }
        public Nullable<int> participants { get; set; }
    }
}
