//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Meeting_Template
    {
        public int tid { get; set; }
        public string meeting_name { get; set; }
        public string meeting_time { get; set; }
        public string meeting_duration { get; set; }
        public string meeting_venue { get; set; }
        public string department { get; set; }
        public string objective { get; set; }
        public Nullable<int> meeting_chairperson { get; set; }
    }
}
