//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Meeting_Details
    {
        public int Task_Id { get; set; }
        public Nullable<int> Meeting_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<int> Chairperson { get; set; }
        public Nullable<int> Participant { get; set; }
        public string Task { get; set; }
        public Nullable<System.DateTime> Completion_Date { get; set; }
        public string Priority { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> Percentage_Completed { get; set; }
        public Nullable<int> Category { get; set; }
        public string is_read_notification { get; set; }
        public Nullable<bool> seen { get; set; }
        public Nullable<bool> is_template { get; set; }
        public Nullable<System.DateTime> NextReviewDate { get; set; }
        public Nullable<int> ReviewFrequencyID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> ChairPersonID { get; set; }
        public Nullable<int> ParticipantID { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public bool baz { get; set; }
    
        public virtual MMS_Meeting_Master MMS_Meeting_Master { get; set; }
    }
}
