//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Employee_Attachment
    {
        public Nullable<int> Id { get; set; }
        public string MMS_FileName { get; set; }
        public string MMS_FileExtension { get; set; }
        public byte[] MMS_File { get; set; }
        public bool IsActive { get; set; }
        public int AttachmentID { get; set; }
    }
}
