//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Login_Master
    {
        public string UserName { get; set; }
        public int Employee_Id { get; set; }
        public bool User_Status { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string password { get; set; }
        public Nullable<bool> Member_Rights { get; set; }
    
        public virtual MMS_Employee_Master MMS_Employee_Master { get; set; }
    }
}
