//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_get_EmployeeDepartments
    {
        public long ID { get; set; }
        public Nullable<int> Employee_Code { get; set; }
        public string User_name { get; set; }
        public int Department_Id { get; set; }
        public string EmailID { get; set; }
    }
}
