//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_get_EmployeeDepartment
    {
        public int EmployeeICode { get; set; }
        public string EmployeeDisplayName { get; set; }
        public int DepartmentICode { get; set; }
        public string EmployeeCorporateEmailId { get; set; }
    }
}
