//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_get_EmployeesTech
    {
        public string EmployeeName { get; set; }
        public string DOJ { get; set; }
        public string EmployeePrimarySkill { get; set; }
        public string Designation { get; set; }
    }
}
