//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Review_Frequency
    {
        public int Freq_Id { get; set; }
        public string Freq_Name { get; set; }
        public Nullable<int> Freq_In_Days { get; set; }
        public string Active_Flag { get; set; }
    }
}
