//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Meeting_Participant
    {
        public Nullable<int> Meeting_Id { get; set; }
        public Nullable<int> Participant_Id { get; set; }
        public string Participant_Name { get; set; }
        public int MeetingParticipantId { get; set; }
    
        public virtual MMS_Meeting_Master MMS_Meeting_Master { get; set; }
    }
}
