//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Meeting_Status_Update
    {
        public Nullable<int> MeetingId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Task { get; set; }
        public Nullable<int> status { get; set; }
        public int MeetingStatusAutoId { get; set; }
        public Nullable<int> TaskId { get; set; }
    }
}
