//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Meeting_Status
    {
        public int Meeting_Status_Employee_Id { get; set; }
        public string Meeting_Status_Task { get; set; }
        public Nullable<int> Meeting_Status_ResponsiblePerson { get; set; }
        public Nullable<System.DateTime> Meeting_Status_Date { get; set; }
        public string Meeting_Status_Comments { get; set; }
        public Nullable<int> Meeting_Status { get; set; }
        public Nullable<int> Meeting_Id { get; set; }
        public string Meeting_Status_Hours { get; set; }
        public Nullable<int> Commented_By { get; set; }
        public Nullable<int> Commented_By_ID { get; set; }
        public int MeetingStatusAutoId { get; set; }
        public Nullable<int> Task_Id { get; set; }
        public Nullable<System.DateTime> Meeting_Date1 { get; set; }
    }
}
